
let posts = [
    {'userProfilePic': 'img/Chisom.jpg',
        'author': 'Chisom Asampte nwanyi',
        'location':'Lasgidi, Nigeria',
        'image':'img/Som post.jpg',
        'description': 'We are still taking orders, order now!',
        'comments':[],
        'imglike': 'img/likeImg.svg',
        'likes': 1001,
        'isliked': false,
        },

    {'userProfilePic': 'img/asiaGirl.jpg',
    'author': 'Chan',
    'location':'Wuhan, China',
    'image':'img/woman-5281129_1280.jpg',
    'description': 'I miss this bustling city',
    'comments':[],
    'imglike': 'img/likeImg.svg',
    'likes': 1001,
    'isliked': false,
    },
    
    {'userProfilePic': 'img/DarkskinGirl.jpg',
    'author': 'Joan',
    'location':'Texas, USA',
    'image':'img/blackburry.jpg',
    'description': 'What a Sunny day',
    'comments':[],
    'imglike': 'img/likeImg.svg',
    'likes': 780,
    'isliked': false,
    },
    
    {'userProfilePic': 'img/benedict.jpg',
    'author': 'Chan',
    'location':'Mexico-City,Mexico',
    'image':'img/mature-woman-850600_1280.jpg',
    'description': 'A little Puff',
    'comments':[],
    'imglike': 'img/likeImg.svg',
    'likes': 56,
    'isliked': false,
    },
    
    {'userProfilePic': 'img/pro1Pix.jpg',
    'author': 'Oscar Nasimento',
    'location':'Brazil',
    'image':'img/pexels-hikaique-109919.jpg',
    'description': 'spot me!',
    'comments':[],
    'imglike': 'img/likeImg.svg',
    'likes': 499,
    'isliked': false,
    },
    
    {'userProfilePic': 'img/EveningWalk.jpg',
    'author': 'Edu Brasil',
    'location':'Obiagu, Enugu',
    'image':'img/sweihuizen-3670176_1280.jpg',
    'description': 'What walking round  city in the evening looks like',
    'comments':[],
    'imglike': 'img/likeImg.svg',
    'likes': 1001,
    'isliked': false,
    },
    
    {'userProfilePic': 'img/Bold&beauty.jpg',
    'author': 'Boko shots',
    'location':'Lagos, Nigeria',
    'image':'img/Bold.jpg',
    'description': 'I miss this bustling city',
    'comments':[],
    'imglike': 'img/likeImg.svg',
    'likes': 1001,
    'isliked': false,
        
    },
];